[package]
<<<<<<< HEAD
name = "first-cargo-program"
=======
name = "first-rust-app"
>>>>>>> 69bd54c (first commit)
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
